version: '3.6'
services:
  elasticsearch:
      image: elasticsearch:7.9.3
      container_name: elastic-7.9.3
      environment:
        - discovery.type=single-node
      networks:
        - elastic
      ports: 
        - "9200:9200"
        - "9300:9300"

  kibana:
      image: kibana:7.9.3
      container_name: kibana-7.9.3
      networks:
        - elastic
      environment:
        - ELASTICSEARCH_HOST=elasticsearch
        - ELASTICSEARCH_PORT=9200
      ports:
        - "5601:5601"
      depends_on: 
        - elasticsearch

networks:
  elastic:
    driver: bridge